### ISSUE TITLE
Ошибка worldMap.o

### ISSUE THREAD

**Issue by Mikael-Gamer100ProKiller** [jesinmat/terminal-strategy-game#1]
Я билдил проект и получил ошибку

`Compiling worldMap.o... src/worldMap.cpp: In member function ‘CWorldTile& CWorldMap::GetTile(size_t, size_t) const’:
src/worldMap.cpp:142:16: error: ‘invalid_argument’ is not a member of ‘std’
  142 |     throw std::invalid_argument("Tile index out of range");
`

теперь хз че делать...

**Comment by Mikael-Gamer100ProKiller** [comment]
я тут нашел вариант, я просто закомментировал ту строку и все сработало, вроде игра работает

**Comment by jesinmat** [comment]
Fixed
